apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-external-url
  namespace: keycloak
data:
  # This will be populated by the init-external-url job
  # or manually after deployment
  KEYCLOAK_EXTERNAL_URL: ""

